# Generated by Django 5.0.6 on 2024-07-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="name",
            field=models.CharField(default="", max_length=120),
            preserve_default=False,
        ),
    ]
