# Generated by Django 5.0.6 on 2024-07-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="skills",
            field=models.CharField(default="", max_length=256),
        ),
    ]
