# Generated by Django 5.0.6 on 2024-07-28 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Following",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_people",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_people",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="following",
            field=models.ManyToManyField(
                related_name="related_to",
                through="scholarapp.Following",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
