# Generated by Django 5.0.7 on 2025-04-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                default="/media/default_icon_white.png", upload_to="uploads/"
            ),
        ),
    ]
