# Generated by Django 5.0.6 on 2024-07-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarapp", "0002_alter_customuser_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="department",
            field=models.CharField(default="", max_length=120),
        ),
    ]
