# Generated by Django 5.0.7 on 2025-04-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarapp", "0002_alter_customuser_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                default="default_icon_white.png", upload_to="uploads/"
            ),
        ),
    ]
