# Generated by Django 5.0.6 on 2024-07-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarapp", "0003_customuser_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="tags",
            field=models.CharField(default="", max_length=256),
        ),
    ]
