# Generated by Django 5.0.6 on 2024-08-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarapp", "0003_remove_customuser_following_followers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="author_str",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="publication",
            name="title",
            field=models.CharField(max_length=350),
        ),
    ]
