# Generated by Django 5.0.6 on 2024-07-25 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scholarapp", "0004_customuser_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="department",
            new_name="position",
        ),
    ]
