# Generated by Django 5.0.6 on 2024-07-25 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scholarapp", "0005_rename_department_customuser_position"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="position",
            new_name="department",
        ),
    ]
