# Generated by Django 5.0.7 on 2024-08-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarapp", "0005_conversation_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="message",
            field=models.TextField(null=True),
        ),
    ]
