# Generated by Django 5.0.7 on 2024-08-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarapp", "0006_message_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="external_link",
            field=models.URLField(null=True),
        ),
    ]
