# Generated by Django 5.0.7 on 2024-09-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarapp", "0007_publication_external_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_info",
            field=models.TextField(null=True),
        ),
    ]
