# Generated by Django 5.0.6 on 2024-07-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarapp", "0007_publication"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="author_str",
            field=models.CharField(default="", max_length=120),
            preserve_default=False,
        ),
    ]
