# Generated by Django 5.0.7 on 2024-09-03 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarapp", "0008_customuser_profile_info"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="profile_info",
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.CharField(default="", max_length=256)),
                ("research_interests", models.CharField(default="", max_length=256)),
                ("rank_link", models.URLField()),
                ("education", models.TextField(default="")),
                ("academic_experience", models.TextField(default="")),
                ("non_academic_experience", models.TextField(default="")),
                ("certifications", models.TextField(default="")),
                ("memberships", models.TextField(default="")),
                ("honors", models.TextField(default="")),
                ("service_activities", models.TextField(default="")),
                ("courses", models.TextField(default="")),
                ("references", models.TextField(default="")),
                ("staff_member_achievements", models.TextField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
