# Generated by Django 5.0.7 on 2024-09-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarapp", "0010_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="department",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.AddField(
            model_name="profile",
            name="development_activities",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="profile",
            name="program",
            field=models.CharField(default="", max_length=256),
        ),
    ]
