# Generated by Django 5.0.7 on 2024-09-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "scholarapp",
            "0011_profile_department_profile_development_activities_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="skills",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="tags",
        ),
        migrations.AddField(
            model_name="profile",
            name="skills",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.AddField(
            model_name="profile",
            name="tags",
            field=models.CharField(default="", max_length=256),
        ),
    ]
