# Generated by Django 5.0.7 on 2024-09-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarapp", "0012_remove_customuser_skills_remove_customuser_tags_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="staff_member_achievements",
            field=models.TextField(default=""),
        ),
    ]
