# Generated by Django 5.0.7 on 2024-09-11 19:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarapp", "0013_alter_profile_staff_member_achievements"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=350)),
                ("description", models.CharField(max_length=512)),
                ("author_str", models.CharField(max_length=256)),
                ("external_link", models.URLField(null=True)),
                ("date_created", models.DateTimeField(null=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("CN", "Conference Paper"),
                            ("JN", "Journal Paper"),
                            ("CNE", "Conference Event"),
                            ("WR", "Conference Event"),
                            ("TH", "Thesis Supervision"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "authors",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Publication",
        ),
    ]
