# Generated by Django 5.0.7 on 2024-09-11 20:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarapp", "0014_event_delete_publication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("CN", "Conference Paper"),
                    ("JN", "Journal Paper"),
                    ("AR", "Article"),
                    ("CH", "Chapter"),
                    ("CNE", "Conference Event"),
                    ("WR", "Workshop"),
                    ("TH", "Thesis Supervision"),
                ],
                max_length=3,
            ),
        ),
    ]
