# Generated by Django 5.0.7 on 2024-09-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarapp", "0015_alter_event_date_created_alter_event_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("CN", "Conference Paper"),
                    ("JN", "Journal Paper"),
                    ("AR", "Article"),
                    ("CH", "Chapter"),
                    ("PP", "Preprint"),
                    ("CNE", "Conference Event"),
                    ("WR", "Workshop"),
                    ("TH", "Thesis Supervision"),
                ],
                max_length=3,
            ),
        ),
    ]
