# Generated by Django 5.0.7 on 2024-09-16 11:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarapp", "0017_alter_event_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="attendees",
            field=models.ManyToManyField(
                blank=True, related_name="attendees", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
