# Generated by Django 5.0.7 on 2024-10-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarapp", "0018_event_attendees"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="description",
            field=models.CharField(default="", max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="conversation",
            name="title",
            field=models.CharField(default="", max_length=120),
            preserve_default=False,
        ),
    ]
