# Generated by Django 5.0.7 on 2024-10-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarapp", "0019_conversation_description_conversation_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="tags",
            field=models.CharField(default="", max_length=256),
            preserve_default=False,
        ),
    ]
