# Generated by Django 5.0.7 on 2024-10-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarapp", "0020_event_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="group_icon",
            field=models.ImageField(
                default="default_group_icon.png", upload_to="media/"
            ),
        ),
    ]
