# Generated by Django 5.0.7 on 2024-10-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarapp", "0027_alter_conversation_group_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="group_icon",
            field=models.ImageField(default="default_icon.png", upload_to="uploads"),
        ),
    ]
