# Generated by Django 5.0.7 on 2024-10-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarapp", "0028_alter_conversation_group_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="group_icon",
            field=models.ImageField(upload_to="uploads"),
        ),
    ]
