# Generated by Django 5.0.7 on 2024-10-26 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scholarapp", "0029_alter_conversation_group_icon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="user_to",
        ),
    ]
