# Generated by Django 5.0.7 on 2024-10-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarapp", "0030_remove_message_user_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="description",
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="title",
            field=models.CharField(max_length=120, null=True),
        ),
    ]
