# Generated by Django 5.0.7 on 2025-01-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarapp", "0032_alter_conversation_group_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(default="default_icon.png", upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="event",
            name="author_str",
            field=models.CharField(default="", max_length=256),
        ),
    ]
