# Generated by Django 5.0.7 on 2025-01-23 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scholarapp", "0033_alter_customuser_avatar_alter_event_author_str"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="profile_url",
        ),
    ]
