# Generated by Django 5.0.7 on 2025-03-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarapp", "0034_remove_customuser_profile_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="faculty",
            field=models.CharField(default="", max_length=256),
        ),
    ]
